[package]
name = "tracing"
version = "0.1.0"
authors = ["Nirvan Tyagi <nirvan.tyagi@gmail.com>"]
edition = "2018"

[dependencies]
aes-soft = "0.3.3"
log = "0.4.6"
rand = "0.6.5"
redis = "0.10.0"
sha3 = "0.8.2"

[dev-dependencies]
env_logger = "0.6.1"
